#ifndef _TOKEN_H_
#define _TOKEN_H_

enum {
	/* Compound operators */
	T_PLUSEQ, T_MINUSEQ, T_STAREQ, T_DIVEQ, T_MODEQ, T_LSHIFTEQ,
	T_RSHIFTEQ, T_ANDEQ, T_OREQ, T_XOREQ,

	T_PLUS, T_MINUS, T_STAR, T_SLASH, T_MODULO,
	T_BOR, T_AMP, T_BXOR, T_BLSHIFT, T_BRSHIFT
	T_LAND, T_LOR, T_NOT,

	T_SEMI, T_ARROW, T_DOT, T_ELLIPSES,

	T_LBRACE, T_RBRACE, T_LBRACKET, T_RBRACKET, T_LPAREN, T_RPAREN,

	/* Primitive types */
	T_BOOL, T_VOID, T_CHAR, T_SHORT, T_INT, T_LONG, T_DOUBLE, T_FLOAT,
	T_COMPLEX, T_IMAGINARY,

	T_ALIGNAS, T_ALIGNOF, T_ATOMIC, T_GENERIC, T_NORETURN, T_STATICASSERT,
	T_THREADLOCAL,

	/* Reserved keywords */
	T_ASM, T_AUTO, T_BREAK, T_CASE, T_CHAR, T_CONST, T_CONTINUE, T_DEFAULT,
	T_DO, T_ELSE, T_ENUM, T_EXTERN, T_FOR, T_GOTO, T_IF, T_REGISTER,
	T_RETURN, T_SIGNED, T_STATIC, T_STRUCT, T_SWITCH, T_SIZEOF, T_TYEPDEF,
	T_UNION, T_UNSIGNED, T_VOLATILE, T_WHILE,
};

#endif /* !_TOKEN_H_ */
